#!/usr/bin/env bash
set -euox pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
cd "$SCRIPT_DIR"

# Start the local container registry
registry/start

# Setup the requirements and run the test pod
kubectl apply -f cluster/rbac.yml -f cluster/secret.yml

run_test_pod() {
    kubectl delete -f cluster/pod.yml || true
    kubectl apply -f cluster/pod.yml
    kubectl wait --for=condition=ready pod/test-pod
}

# Run the first test pod, mirror should be found
run_test_pod

# Run the second test pod, mirrors should be empty
echo "" | sudo tee /etc/containers/registries.conf
run_test_pod

# Run the third test pod, mirror file does not exist
sudo rm /etc/containers/registries.conf
run_test_pod

# Do assertions
# TODO: Expand them when https://github.com/cri-o/cri-o/pull/9463 got merged
GOT=$(mktemp)
EXPECTED=$(mktemp)
trap 'rm "$GOT" "$EXPECTED"' EXIT

sudo journalctl _COMM=credential-prov --since "5 minutes ago" | sed -E 's;.*.go:[0-9]+:\s(.*);\1;' >"$GOT"

# First test result
cat >"$EXPECTED" <<EOL
Running credential provider
Reading from stdin
Got stdin, parsing JSON as CredentialProviderRequest
Parsed credential provider request for image "docker.io/library/nginx"
Parsing namespace from request
Matching mirrors for registry config: /etc/containers/registries.conf
Got mirror(s) for "docker.io/library/nginx": "localhost:5000"
Getting secrets from namespace: default
Got 1 secret(s)
Parsing secret: my-secret
Found docker config JSON auth in secret "my-secret" for "http://localhost:5000"
Checking if mirror "localhost:5000" matches registry "localhost:5000"
Using mirror auth "localhost:5000" for registry from secret "localhost:5000"
Wrote auth file to /etc/crio/auth/default-7e59ad64326bc321517fb6fc6586de5ee149178394d9edfa2a877176cdf6fad5.json with 1 number of entries
Auth file path: /etc/crio/auth/default-7e59ad64326bc321517fb6fc6586de5ee149178394d9edfa2a877176cdf6fad5.json
EOL

# Second test result
cat >>"$EXPECTED" <<EOL
Running credential provider
Reading from stdin
Got stdin, parsing JSON as CredentialProviderRequest
Parsed credential provider request for image "docker.io/library/nginx"
Parsing namespace from request
Matching mirrors for registry config: /etc/containers/registries.conf
No mirrors found, will not write any auth file
EOL

# Third test result
cat >>"$EXPECTED" <<EOL
Running credential provider
Registries conf path "/etc/containers/registries.conf" does not exist, stopping
EOL

diff "$GOT" "$EXPECTED"

# Assert CRI-O logs
sudo journalctl -u crio | grep -q "Using auth file for namespace default"
podman logs registry &>output
grep -q "authorized request" output
